INSERT INTO PRODUCTS (NAME,DESCRIPTION,PRICE,CREATE_DATE,UPDATED_DATE	) VALUES
 ('Think-pad x1', 'Lenovo Think-Pad X1 - intel core I7 - 16GB memory - 512gb ssd',350.0,CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP );

 INSERT INTO PRODUCTS (NAME,DESCRIPTION,PRICE,CREATE_DATE,UPDATED_DATE	) VALUES
  ('MacBook Pro M1', 'Apple Laptop - M2 chip: 13-inch Retina display, 8GB RAM',600.0,CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP );



